### ISSUE TITLE
inter_proc_comm_mpi.cc not found

### ISSUE THREAD

**Issue by zhoujuncc1** [naoyam/physis#10]
When I build with MPI-CUDA mode, it shows error:

```
CMake Error at /home/ec2-user/share/cmake-2.8/Modules/FindCUDA.cmake:1441 (add_library):
  Cannot find source file:
    inter_proc_comm_mpi.cc
Call Stack (most recent call first):
  runtime/CMakeLists.txt:74 (cuda_add_library)
```

In runtime, there is no file called inter_proc_comm_mpi.cc

**Comment by naoyam** [comment]
Thanks for reporting the error. Unfortunately, the MPI-CUDA backend is broken now, and I've been working on fixing it. I expect it'll be done within a week or so.

**Comment by zhoujuncc1** [comment]
Thanks for the prompt reply. I'm looking forward to the good news.

Best Regards,
ZHOU Jun

**Comment by zhoujuncc1** [comment]
How is the progress now?
Thanks.

**Comment by naoyam** [comment]
Taking longer than expected, but some of the features should now work. You
can take a look at branch feature/mpi-cuda-fix for the latest development.
Depending on your interest, this branch may work for you.

**Comment by naoyam** [comment]
This is now closed in the develop branch.
