### ISSUE TITLE
ROSE not available

### ISSUE THREAD

**Issue by zhoujuncc1** [naoyam/physis#17]
Now the ROSE project is not available from the given website. Actually the website is not accessible any longer. Please give the updated ROSE install instructions.
Thanks.

**Comment by naoyam** [comment]
Thanks for reporting the change of ROSE download availability. I'll update the instructions.

**Comment by naoyam** [comment]
The current latest revision should fix this problem. See 39ee5250a2d5baa545ca03e7c5c9aa9c81f1ab19.

Previously we used a tgz package of ROSE, which is not available for downloads anymore and is replaced by the git repository at http://github.com/rose-compiler/edg4x-rose. See docs/rose.md for how to set up a ROSE installation.
